import app
import chr
import chrmgr
import skill

JOB_WARRIOR		= 0
JOB_ASSASSIN		= 1
JOB_SURA		= 2
JOB_SHAMAN		= 3
JOB_WOLFMAN	= 4

RACE_WARRIOR_M	= 0
RACE_ASSASSIN_W	= 1
RACE_SURA_M		= 2
RACE_SHAMAN_W	= 3
RACE_WARRIOR_W	= 4
RACE_ASSASSIN_M	= 5
RACE_SURA_W		= 6
RACE_SHAMAN_M	= 7
RACE_WOLFMAN_M	= 8

PASSIVE_GUILD_SKILL_INDEX_LIST = ( 151, )
ACTIVE_GUILD_SKILL_INDEX_LIST = ( 152, 153, 154, 155, 156, 157, )

